### ISSUE TITLE
What is "remember me?" for?

### ISSUE THREAD

**Issue by 11v1** [jakubgarfield/Bonobo-Git-Server#842] opened 2019-07-17 04:37 UTC
Hi.

My problem is that users doesn't log out automatically on browser restart or timeout set in web.config. The only way to log out is to press "Sign Out". What am I doing wrong?

**Comment by KlomDark** [comment] 2019-12-13 04:52
The "Remember Me" checkbox (If checked before the user enters their ID and Password) sets a cookie during login that will stay on the users browser. When they connect again in the future, Bonobo looks for that cookie: 

- If the cookie **exists** (And has not expired), then the user does not have to re-enter their credentials. 
- If the cookie **does not exist**, then the user is prompted for their id & password. 

In the case of them having the "remember me" cookie:

If you check on the server, once the timeout occurs, their session is dead. But when they reconnect with the cookie, then they are getting a new session ID. The remember me cookie lives on the user's browser so it can give the illusion that you are seeing that they are not ever logging out. Their session will still time out on the server side, so they are effectively logged out in the meantime.

The behavior you are seeing with "Sign Out" is _as expected_. Sign Out deletes the "Remember Me" cookie, so will force them to enter their credentials the next time they connect to Bonobo with their browser. If they do not sign out, then the cookie is presented the next time, making it appear as if they never logged out.

Suggest this is closed as **By Design**.

**Closed** 2020-07-22 12:30 UTC
