### ISSUE TITLE
When will version 6 be released?

### ISSUE THREAD

**Issue by NgYueHong** [jakubgarfield/Bonobo-Git-Server#587] opened 2016-07-20 02:06 UTC
May I know when will version 6 plan to be released?

**Comment by RedX2501** [comment] 2016-07-21 10:09
We are trying to iron out the last few problems but there is no date
currently.

**Comment by NgYueHong** [comment] 2016-09-19 03:57
What happen to this project? The last commit was 2 months ago?

**Comment by Trapulo** [comment] 2016-09-19 19:46
I really hope is alive...

**Comment by willdean** [comment] 2016-09-19 20:26
I don't think it's dead, and a bunch of people did a lot of work on 6.x which is now basically done.   There are some open issues around AD integration which are very difficult/tiresome for the current devs to test, and not everyone who reports AD issues is able to keep testing and retesting on behalf of the project.

The original owner of the project is not as active on it as he once was, and that probably holds it back rather, as these things do run more smoothly with a benevolent dictator-for-life at the helm.

If you're not using AD, then there's probably no reason not to give 6 a try as it is.  (Take a decent database backup first!)

**Comment by jakubgarfield** [comment] 2016-09-19 21:37
@willdean any idea what would help the project in terms of ownership? I'm pretty sure that it's time for me to move on as I basically did it for the past few months and left you, @RedX2501, @larshg and @latop2604 to take care of the project.

**Comment by willdean** [comment] 2016-09-19 22:08
@jakubgarfield That's a good question - I don't personally want any more responsibility for it, and in scale/complexity (particularly of the auth/identity test matrix) I think it's rather outgrown every individual who's been involved.

@RedX2501 was doing a fantastic job of keeping it all going, but I rather abandoned him because of work commitments earlier in the year (which have now passed) and now he seems to be gone.

The AD stuff is a real problem - I don't think the big rework this time last year was an unqualified success, but I don't understand the history of it, and it's really difficult to test / support.

Maybe you should just release 6.0 as-is (maybe call it 'beta') and then publicly bow-out - whoever feels like it can do bug-fix/support on that and then we'll see what happens.

**Comment by Trapulo** [comment] 2016-09-20 14:03
Releasing a 6.0 with well known problems is not a great idea IMHO. For example, I use AD integration. If I upgrade the app and it starts to create problems I will lose confidence with that app and maybe will stop using it.
I don't know what is this AD problem in detail. If there is a way to maintain existing functionalities without trouble, a beta can be acceptable waiting for new feature.

**Comment by willdean** [comment] 2016-09-20 14:47
@Trapulo Do you have AD issues you know about with the current version (either 6 or 5.x)?  Would you be able to help debug them?

**Comment by Trapulo** [comment] 2016-09-20 14:59
I'm using 5.2.0 with AD and it works really well.
If I can help, I can do some test if it's not too complex.

**Comment by willdean** [comment] 2016-09-20 15:04
@Trapulo You can get the latest build from https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/artifacts - if you'd like to try that, take a backup of everything in you 5.2 install first.

Please open another issue if you have any problems.

**Comment by Trapulo** [comment] 2016-09-20 20:09
@willdean  tried to update to last build. Lost every repo details (users permissions, logos, and other details) but all seems ok. Tried a little sync and commit from Visual Studio and all seems ok. Is there some specific trouble may I search?

**Comment by willdean** [comment] 2016-09-20 20:38
@Trapulo Could you look at case #602 please?

**Comment by RedX2501** [comment] 2016-09-25 20:04
@willdean Hi, I have taken a step back also mostly due to my current work load + I moved back from abroad so I got a life going on again. Plus I'm actually waiting for your feedback/testing on #580. If I know it's good we are almost done with the todo list for 6.0.

**Comment by larshg** [comment] 2017-02-10 10:27
@Trapulo Can you try out #644 to see if you can upgrade without loosing repos detail. Ofc. make sure to backup everything :)

**Comment by willdean** [comment] 2017-02-10 11:02
@larshg I don't think @Trapulo still has his original 5.2 install upgrade with, sadly.

**Comment by larshg** [comment] 2017-02-10 11:05
Ah. Well, then maybe just test that the configuration is still working :D

**Comment by Trapulo** [comment] 2017-02-10 13:48
Yes, I lost old 5.x env. I don't understand: do I need to try the new build (currently I run 6.0.0.452)

**Comment by parappsys** [comment] 2017-03-23 18:56
Trapulo, would you be able to point me in the right direction with AD integration? I've configured the groups in AD and entered the AD settings in web.config, and I have the IIS app pool for Bonobo running as a domain user that is able to query LDAP, but I can't log in with any Admin group user. Regular users are able to log in, though. The worst part is that with AD integration enabled, I can't log in with the internal admin user, so there's essentially no way to administer the installation with AD integration enabled. I don't see a way to add a domain user and some sort of hashed password in web.config, which is why I was running the app pool as a domain query user.

We are running 5.2 on IIS 8.5. I'm willing to try 6 just for fun, but I'd like for this to eventually be used in production and don't want to use a beta. Thanks!

**Comment by willdean** [comment] 2017-03-23 19:15
@parappsys Please, please use 6.0 - the only reason it's a 'beta' is that we're struggling to find people to test the AD integration.  

Assuming you're able to create groups in your AD, add yourself to a group called, for example, GitAdmins and then in web.config make sure you have a line like:

```
<add key="ActiveDirectoryRoleMapping" value="Administrator=GitAdmins" />
```

That will specify that every member of AD group "GitAdmins" is given the role "Administator" in Bonobo.

Obviously you can call it "BonoboAdmins" or something else if you like.

**Comment by parappsys** [comment] 2017-03-23 19:20
@willdean , here's what I have:
<add key="ActiveDirectoryRoleMapping" value="Administrator=GitAdmins" />

My domain account is a member of the GitAdmins group, as is one other account. Neither of those can successfully log in, but users in the GitUsers group can log in. I think I saw another ticket with someone mentioning this.

I've DLed 6.0 and will overwrite the current install to see if this resolves the issue. BRB

**Comment by larshg** [comment] 2017-03-23 20:17
Are the admins also in the membergroupname AD group?

**Comment by willdean** [comment] 2017-03-23 20:30
@parappsys Lars makes a really good point there - the admins need to be in *both* groups.

**Comment by Trapulo** [comment] 2017-03-24 09:17
Mi config is
    <add key="ActiveDirectoryDefaultDomain" value="myaddomain.local" />
    <add key="ActiveDirectoryMemberGroupName" value="Git Users" />
    <add key="ActiveDirectoryTeamMapping" value="Developers=Git Users" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=Git Admins" />

Is not important to run IIS app pool as domain user (in fact I discourage this: use the default isolated pool users).
My admin user is both in AD group "Git Users" and "Git Admins"

Config was same in 5 and 6 (I'm using 6.0.0.452) I think.

bye

**Comment by parappsys** [comment] 2017-04-03 18:33
I changed the app pool to use the AP Identity and added the GitAdmin group to the membership of GitUsers. I also directly added my name after that didn't work with no change.

My config is like this:
`   <add key="MembershipService" value="ActiveDirectory" />
    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="GitUsers" />
    <add key="ActiveDirectoryDefaultDomain" value="myaddomain.local" />
    <add key="ActiveDirectoryTeamMapping" value="Developers=GitTeam" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=GitAdmins" />`

I can log in, but there is no admin role for me. Clicking on the user icon results in an "Item wasn't found".
![image](https://cloud.githubusercontent.com/assets/20976424/24624442/dd36fd78-1879-11e7-823a-c0e7ff8c8792.png)

Judging by the 0s in the URL, my user isn't being added.

When I look at the ADBackend\Users folder, I see two entries. None are mine, but one belongs to a user in the GitAdmins group, and the other belongs to a user in the GitUsers group. Curiously, it appears to be the user who is listed first alphabetically in each group, and then none are added after that.

**Comment by willdean** [comment] 2017-04-03 18:48
@parappsys It looks as though there may be a problem during the import of the AD users which is stopping them all being added.

Can you look at the end of the log file in app_data and see if there are any exception messages?  (Don't worry about sqlite messages, they're not errors)

**Comment by parappsys** [comment] 2017-04-03 19:14
The only error seemed to be caused by me uncommenting the GitTeam line but not having an AD group for it. Created one and started with a clean install, but I'm still just seeing the top 2 user accounts again. This time there is not a log file in app_data, though.

**Comment by willdean** [comment] 2017-04-03 19:39
@larshg Any ideas?  I thought we'd got rid of all the silent failures in the AD import, so I'm not sure what's happening here.

**Comment by parappsys** [comment] 2017-04-03 20:09
I recreated the site and just left my domain account in GitAdmins. GitAdmins is also a member of GitUsers. When I log in, I have the same empty account, no error log, and the Users directory is completely empty.

**Comment by willdean** [comment] 2017-04-03 20:24
It is the admin user which should be a member of GitUsers and GitAdmins.  You shouldn't make GitAdmins a member of GitUsers.  (I didn't even know you could make a group a member of another group...)

**Comment by parappsys** [comment] 2017-04-03 20:31
Started fresh, only my account in GitUsers and GitAdmins (directly via my account). I log in and can see the ADBackend directly get created. There's no error log, and when I go into the ADBackend\Users directory, I only see the first account in the GitUsers AD group. My account is completely skipped. Does the account that initially logs in via the web interface required to have local rights on the server?

**Comment by willdean** [comment] 2017-04-03 20:38
If there is only your account in GitUsers and GitAdmins, where is the other account which gets added coming from?

I'm not an AD expert by any means, but I wouldn't expect any of the users to need rights on the server.

All the users in the GitUsers group should be added, yes, though if there is only your account in GitUsers and GitAdmins, obviously you would only expect to see one account.

**Comment by parappsys** [comment] 2017-04-03 20:42
I should have been more clear. I am the only account in the GitAdmin and GitUsers group. The single user that populates the Users directory comes from the GitUsers group. There are 5 accounts in there, but only the first one is added.

I added the Developer Admin domain account to the GitAdmins group, and after restarting the site I can see the admin role features. The Users page shows 2 usernames, one is .local (the Developer Admin with no email account) and the other ends with .com. This is because in order to integrate with Office 365, the primary user logon names have to match the email address. The legacy name still uses domain\username. Would this matter?

**Comment by willdean** [comment] 2017-04-03 20:55
@parappsys I think the domain\username stuff might be significant - there have been endless games involved with AD domain names which I have not been directly involved with and don't fully understand.   @larshg is the nearest thing we have to anyone who understands AD and has a test setup of some kind.  

I'm sorry we're struggling to help you here, but there is basically no test story for AD other than setting up a box running Windows Server and configuring it as a domain server, then hoping it's the same configuration as whatever someone else is having a problem with - this makes it terribly difficult to help. 
 There is no overlap between the current, active, contributors to Bonobo and the people who did a massive drive-by commit of a completely re-written version of the AD code about 2 years ago - this was poor quality and had some odd-seeming design decisions the rationale for which is now lost.

We have tried to improve things, but clearly not enough yet.  I'm particularly sad that we're still suffering failures without them being logged, because I thought we'd improved that significantly.

As a test, are you able to add usernames with conventional user\domain logons to see if they work better?

**Comment by parappsys** [comment] 2017-04-04 14:13
When I log in with the Dev Admin account that has admin rights and head to the user page, there aren't any options to add a user manually.

![image](https://cloud.githubusercontent.com/assets/20976424/24660677/26205b84-191e-11e7-86c3-706b2478e1f7.png)

Is it possible to create the json files in Users manually?

I have a full domain just lying around with a spare server, so I'm happy to test out updates.

**Comment by willdean** [comment] 2017-04-04 14:37
Unfortunately when using AD membership, Bonobo completely replaces its own (SQLite-based) membership storage with the json-based AD import.  I've never been able to find out why this was done like that, but a side-effect is that only the AD import is able to create users.

I understand your privacy concerns, but could you show us exactly what one of your users looks like in AD - change the names/domain names/whatever for privacy, but preserve the syntax precisely so that we can see if we can see why it's breaking the import.

Is it too much to ask that you could run Bonobo under Visual Studio and step through the AD import?

**Comment by larshg** [comment] 2017-04-18 08:32
@parappsys Are you able to debug this and maybe come with suggestions to what is causing this? Alternatively I'll try to add some more logging with the new framework @willdean added, to get more info to work with.

**Comment by larshg** [comment] 2017-04-18 08:33
@parappsys Maybe create a new proper issue aswell - I'll close this as the topic is about releasing of 6.0 which has already happend.

**Closed by larshg** 2017-04-18 08:33 UTC
