### ISSUE TITLE
Allow anonymous users to browse public repositories

### ISSUE THREAD

**Issue by glacasa** [jakubgarfield/Bonobo-Git-Server#226] opened 2015-03-16 18:07 UTC
I think it would be a good idea to allow anonymous users to display the list of public repositories on the home page, instead of asking to login.

Also, I noted that repositories with the "Anonymous" option checked can't be seen in the browser.

I started to work on this feature on this branch :
https://github.com/glacasa/Bonobo-Git-Server/tree/anonymous-listing
but I'm not sure I'm doing it the right way.

**Comment by jakubgarfield** [comment] 2015-03-18 19:18
Duplicate of #77

**Closed by jakubgarfield** 2015-03-18 19:18 UTC
