### ISSUE TITLE
ADMembershipService throwing error when using build# 2f9a001

### ISSUE THREAD

**Issue by chrismdev** [jakubgarfield/Bonobo-Git-Server#407] opened 2016-01-13 22:31 UTC
I had to change this line:

using (UserPrincipal user = UserPrincipal.FindByIdentity(principalContext, username))

to this:

using (UserPrincipal user = UserPrincipal.FindByIdentity(principalContext, username.Replace("!",@"\")))

**Comment by RedX2501** [comment] 2016-01-14 02:47
How did you provide your Username for git? The intended way is domain\username

**Comment by chrismdev** [comment] 2016-01-14 03:57
I am using the ActiveDirectory membership service so I I only need to supply the ActiveDirectoryMemberGroupName to allow a list of users. Here is my config:

    <add key="AuthenticationProvider" value="Windows" />
    
    <add key="MembershipService" value="ActiveDirectory" />
    <add key="ActiveDirectoryDefaultDomain" value="xxxxxx" />
    <add key="ActiveDirectoryBackendPath" value="~\App_Data\ADBackend" />
    <add key="ActiveDirectoryMemberGroupName" value="GroupName" />
    <add key="ActiveDirectoryTeamMapping" value="Developers=GroupName" />
    <add key="ActiveDirectoryRoleMapping" value="Administrator=Domain Admins" />

**Comment by RedX2501** [comment] 2016-01-14 04:23
Oh I see. Can you please provide a PR?

**Comment by chrismdev** [comment] 2016-01-14 05:13
I just did a quick check and AD does allow you to have an ! in the username, so I think my fix is not correct.

I think the solution would be to only convert the first ! in the username. Yes will submit a PR.

**Comment by RedX2501** [comment] 2016-01-14 05:47
Although many services will allow ! in the usernames the PR I submited will not like them as I do a Replace("!", "\\") in many places. Maybe you can fix those too, to only replace the first occurrence?

**Comment by chrismdev** [comment] 2016-01-14 22:30
This is my first PR so please be gentle.

I changed all the Replaces() I could find but left the views alone.

**Comment by RedX2501** [comment] 2016-01-16 11:44
You should fix the replace in the Views to for consistency IMHO.

**Comment by chrismdev** [comment] 2016-01-20 03:26
Will do this as soon as I get a chance

**Comment by RedX2501** [comment] 2016-01-25 11:14
Just a heads up that this will probably be fixed by #426

**Comment by RedX2501** [comment] 2016-02-21 16:10
@chrismdev Can please check that this is fixed on latest master? https://ci.appveyor.com/project/jakubgarfield/bonobo-git-server/build/artifacts

# Please backup your Database as latest master will upgrade it to a format not compatible with 5.1.1.

**Comment by chrismdev** [comment] 2016-02-21 21:58
I deleted my ADBackend folder and Bonobo.Git.Server.db and got this error in the log Bonobo.Git.Server.Errors.log:

w3wp.exe Error: 0 : Error occured and caught in Global.asax - System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.TryParseGuidWithNoStyle(String guidString, GuidResult& result)
   at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)
   at System.Guid.Parse(String input)
   at Bonobo.Git.Server.UserExtensions.Id(IPrincipal user) in C:\projects\Bonobo-Git-Server\Bonobo.Git.Server\Extensions\UserExtensions.cs:line 35
   at ASP._Page_Views_Shared__Layout_cshtml.Execute() in c:\inetpub\wwwroot\Git\Views\Shared\_Layout.cshtml:line 35
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.WebPages.WebPageBase.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer)
   at System.Web.WebPages.WebPageBase.Write(HelperResult result)
   at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)
   at System.Web.WebPages.WebPageBase.PopContext()
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by willdean** [comment] 2016-02-21 22:05
Can you clear your browser cookies for the Bonobo server address?   Sounds like the browser might be claiming you're logged-in to an account which no longer exists.  (I'll try and repro this here anyway)

**Comment by chrismdev** [comment] 2016-02-21 22:11
Does this look right? we seem to be trying to cast a Upn to a guid in the UserExtensions class?

user.GetClaim(ClaimTypes.Upn);

**Comment by chrismdev** [comment] 2016-02-21 22:14
Yeah that looks like the problem. My Upn looks like this:  chris@domain.local

**Comment by chrismdev** [comment] 2016-02-21 22:19
Apologies, after I cleared that cookie it started working

**Comment by willdean** [comment] 2016-02-21 22:20
@chrismdev Cool - but we need to handle that better.

**Comment by RedX2501** [comment] 2016-02-21 22:30
With the new integration tests we can probably fake a cookie. Not sure how
to test the AD part tho.
Am 22.02.2016 03:50 schrieb "Will Dean" <notifications@github.com>:

**Comment by chrismdev** [comment] 2016-02-22 00:21
Not sure if I should create a new issue or add this in here. It no longer determines that I am in the administrators role. I'll dig in to this when I have a bit of time.

**Comment by RedX2501** [comment] 2016-02-22 04:21
Same as #459

**Closed by RedX2501** 2016-02-22 04:21 UTC
Labels: is:awaiting-reply, is:bug

**Comment by RedX2501** [comment] 2016-02-22 05:01
@chrismdev Can you please chime in on that thread? Maybe we are able to reproduce it with your help.
