### ISSUE TITLE
Preview of this file is not supported=file with Ending .PLS

### ISSUE THREAD

**Issue by allipierre** [jakubgarfield/Bonobo-Git-Server#351] opened 2015-11-05 09:48 UTC
Hey,
 Does somebody has any idea? 
 Preview of this file is not supported by PKG_WERK2.pls .
 I have a File With Ending .pls. Preview of this file is not supported for this File. Can Somebody help me?
 Thank you

**Comment by jakubgarfield** [comment] 2015-11-05 19:14
Duplicate of #348

**Closed by jakubgarfield** 2015-11-05 19:14 UTC
