### ISSUE TITLE
Non-admin user can modify info in User page and in Team page

### ISSUE THREAD

**Issue by mrloddo** [jakubgarfield/Bonobo-Git-Server#687] opened 2017-05-07 04:55 UTC
Hi all,
I've already tested a recent version of Bonobo Server. Now the AD login works fine using Windows auth and internal membership.
I found now a non-admin user is able to change, delete all users and team info. The account is able to elevate itself to administrator role.

Marco

**Comment by willdean** [comment] 2017-05-07 19:24
@mrloddo Thanks for this - are you saying that the account could delete all users before you elevated it, or that somehow you elevated it first?

Could you perhaps give us a set of steps to reproduce this, starting with when you created the user in the internal membership system?

**Comment by larshg** [comment] 2017-05-09 15:24
I have verified this - a user which should not have admin privileges, does in fact have these. I'll try narrow it down where and why this happens.

**Comment by larshg** [comment] 2017-05-10 09:36
The error occurs only on first login - since the user is not found in the database when the claims is queried [here](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Owin/WindowsAuthenticationHandler.cs#L50) - the user is looked up on the AD server and a new ClaimsIdentity is [created](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Owin/WindowsAuthenticationHandler.cs#L73), with info from AD and double [admin](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Owin/WindowsAuthenticationHandler.cs#L89-L90) claims.

This is then set in the authentication [ticket](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Owin/WindowsAuthenticationHandler.cs#L99) - and therefore the use has admin rights immediately.

However the user is only having the role assigned if the flag or there are only 2 users in the database [here](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Controllers/AccountController.cs#L204)

Hence on subsequent logins the users claims will queried from the database, where the user doesn't have admin rights.

If we remove the two lines adding the Administrator rights, the user won't have those when redirected to the index page, since the Authentication ticket is not updated with the newly acquired adminrights created in the ADCreateUser.

I don't know if it is possible to add the claim to the ticket or if we should clear it and force the user to logon again (which should happen automatically if the browser trust the server and uses NTLM/windows logon) ?

@willdean do you have any good ideas?

**Comment by willdean** [comment] 2017-05-10 11:24
@larshg Awesome detective work (and links to the lines in the code!)

* The double role addition just looks like a simple mistake when we went from string literals to using the Definitions.Role.xxx constants.

* Is the heart of the issue that the user must be temporarily an administrator so that they can add themselves?   I understand your investigation enough to see how they're being set as admin, but I don't think I'm clear why they need to be.

If we can avoid new users needing to be admin at all (even temporarily), then could the code at https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Owin/WindowsAuthenticationHandler.cs#L89 could do a proper role/group lookup and set them as admin correctly?

It also feels to me that the code at https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Controllers/AccountController.cs#L204 might be some kind of holdover from before the role/group stuff was done for AD?   There is already a proper mechanism for AD users to be divided into "Admins" and "non-Admins" - why do we need this sort of hack as well?

**Comment by larshg** [comment] 2017-05-10 11:42
Because if you want to use Windows authentication and and internal DB - you will not enable the AD part, ie. `RoleNameToGroupNameMapping` etc. [These](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/web.config#L29-L35) lines would be commented.

**Comment by willdean** [comment] 2017-05-10 11:53
Ok, right I get it - that makes sense.

Interestingly, `AccountController.ADCreateUser` calls `ADHelper.GetUserPrincipal` which potentially relies on `ActiveDirectoryDefaultDomain` which is, as you've said, commented-out in this scenario.

Just a suggestion here, but perhaps the real fix is to try to bring WinAuth+InternalMembership a little bit closer to full-AD and use more of those web.config settings?   If we're already using `ActiveDirectoryDefaultDomain` then would it be so wrong to use the role/group membership options too?

**Comment by larshg** [comment] 2017-05-10 13:16
Well, if we add the "last few lines" then the option of internal db is non-existing? Then you can't change who is admins etc. without having to bug a admin in the cooperation, which might be tiresome.

I guess the ActiveDirectoryDefaultDomain, should also be a part that can be used with windows authentication, to correctly contact the appropriate server, if there is multiple domains etc.

**Comment by willdean** [comment] 2017-05-10 13:24
@larshg Yes, good point.

So, if we make the following two changes:

1. Don't give anybody an admin role at [this](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Owin/WindowsAuthenticationHandler.cs#L89-L90) point.  

Then

2. If at [this](https://github.com/jakubgarfield/Bonobo-Git-Server/blob/master/Bonobo.Git.Server/Controllers/AccountController.cs#L204) point we *do* decide that a user needs to be admin, then after we've done the `AddUserToRoles` bit we do one of two things:
    a. Add the admin role to their existing claims identity (if we can work out how to do that properly)
or 
    b. Log them off so that they have to log in again (which should be painless) and then they get the proper admin role from the database.

Am I now on the right track?

**Comment by larshg** [comment] 2017-05-10 13:31
Yes, I think that is our options. Alternatively we can decide it by querying the database where the roles are just added, and depending on the claims,  the database is updated acordingly in ADCreateUser.

So writing on phone so it might be a little short, but hope you get my point :-) ?

**Comment by willdean** [comment] 2017-05-10 13:32
@larshg Yup - I'm just going to put in a PR - hopefully you can review / test with your AD setup

**Comment by willdean** [comment] 2017-05-14 07:49
Fixed in #691

**Closed by willdean** 2017-05-14 07:49 UTC
